name: loading_button
description: A new Flutter package for loading button.
version: 0.0.1
author: Athira Greejith
homepage: https://github.com/AugustaHitech-Projects/ah_flutter_components/tree/loading_button

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

